AllCops:
  TargetRubyVersion: 2.3

  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - !ruby/regexp /old_and_unused\.rb$/

  DisplayCopNames: true

Rails:
  Enabled: true

Style:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

# Supports --auto-correct
Lint/EndAlignment:
  Description: Align ends correctly.
  Enabled: true
  AlignWith: keyword
  SupportedStyles:
  - keyword
  - variable
  - start_of_line
  AutoCorrect: false
